# If you change the FLASK_PORT, do not forget to change it in ports and healthcheck as well.
services:
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      BOOK_LANGUAGE: en
    ports:
      - 8084:8084
    # Uncomment the following lines if you want to enable healthcheck
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:8084/request/api/status"]
    #  interval: 30s
    #  timeout: 30s
    #  retries: 3
    #  start_period: 5s
    restart: unless-stopped
    volumes:
    # This is where the books will be downloaded to, usually it would be 
    # the same as whatever you gave in "calibre-web-automated"
      - /home/youcef/docker_app/ingest:/cwa-book-ingest
